In [1]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv ("Downloads/nasa-asteroids-classification/nasa.csv")

In [3]:
del data ['Est Dia in M(min)']
del data ['Est Dia in M(max)']
del data ['Est Dia in Miles(min)']
del data ['Est Dia in Miles(max)']
del data ['Est Dia in Feet(min)']
del data ['Est Dia in Feet(max)']
del data ['Relative Velocity km per hr']
del data ['Miles per hour']
del data ['Miss Dist.(lunar)']
del data ['Miss Dist.(kilometers)']
del data ['Miss Dist.(miles)']
del data ['Orbiting Body']
del data ['Equinox']
del data ['Orbit Determination Date']
del data ['Close Approach Date']
data.head

<bound method NDFrame.head of       Neo Reference ID     Name  Absolute Magnitude  Est Dia in KM(min)  \
0              3703080  3703080              21.600            0.127220   
1              3723955  3723955              21.300            0.146068   
2              2446862  2446862              20.300            0.231502   
3              3092506  3092506              27.400            0.008801   
4              3514799  3514799              21.600            0.127220   
5              3671135  3671135              19.600            0.319562   
6              2495323  2495323              19.600            0.319562   
7              2153315  2153315              19.200            0.384198   
8              2162463  2162463              17.800            0.732074   
9              2306383  2306383              21.500            0.133216   
10             3444370  3444370              22.400            0.088015   
11             3448992  3448992              25.800            0.01838

In [4]:
data.shape

(4687, 25)

In [5]:
features = data.iloc [:, 0:24]
labels = data.iloc [:, [24]]

In [7]:
scaler = MinMaxScaler()
scaler.fit (features)
features_transform = scaler.transform (features)
print (features_transform)

[[0.95575717 0.95575717 0.49856734 ... 0.92250218 0.7358251  0.25823873]
 [0.96747507 0.96747507 0.48424069 ... 0.88054176 0.48271958 0.38871266]
 [0.2505967  0.2505967  0.4364852  ... 0.91779041 0.81377721 0.24227093]
 ...
 [0.98754788 0.98754788 0.55109838 ... 0.93839019 0.56540591 0.22297844]
 [0.98755125 0.98755125 0.50811843 ... 0.9369919  0.56547209 0.23428006]
 [0.99499344 0.99499344 0.3796084  ... 0.94046227 0.51350273 0.23784536]]


C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
pca = PCA (n_components = 20)
principle_components = pca.fit_transform (features_transform)
#principle_components = pca.fit_transform (features)
principleDf = pd.DataFrame(data = principle_components)

In [9]:
features_transform

array([[0.95575717, 0.95575717, 0.49856734, ..., 0.92250218, 0.7358251 ,
        0.25823873],
       [0.96747507, 0.96747507, 0.48424069, ..., 0.88054176, 0.48271958,
        0.38871266],
       [0.2505967 , 0.2505967 , 0.4364852 , ..., 0.91779041, 0.81377721,
        0.24227093],
       ...,
       [0.98754788, 0.98754788, 0.55109838, ..., 0.93839019, 0.56540591,
        0.22297844],
       [0.98755125, 0.98755125, 0.50811843, ..., 0.9369919 , 0.56547209,
        0.23428006],
       [0.99499344, 0.99499344, 0.3796084 , ..., 0.94046227, 0.51350273,
        0.23784536]])

In [10]:
features

Neo Reference ID     Name  Absolute Magnitude  Est Dia in KM(min)  \
0              3703080  3703080              21.600            0.127220   
1              3723955  3723955              21.300            0.146068   
2              2446862  2446862              20.300            0.231502   
3              3092506  3092506              27.400            0.008801   
4              3514799  3514799              21.600            0.127220   
5              3671135  3671135              19.600            0.319562   
6              2495323  2495323              19.600            0.319562   
7              2153315  2153315              19.200            0.384198   
8              2162463  2162463              17.800            0.732074   
9              2306383  2306383              21.500            0.133216   
10             3444370  3444370              22.400            0.088015   
11             3448992  3448992              25.800            0.018389   
12             3611400  3611400              25.000            0.026580   
13             2162854  2162854              19.100            0.402305   
14             3446396  3446396              18.800            0.461907   
15             3764806  3764806              25.200            0.024241   
16             3314405  3314405              20.000            0.265800   
17             3426410  3426410              21.000            0.167708   
18             3666785  3666785              22.300            0.092163   
19             3702321  3702321              22.700            0.076658   
20             3719196  3719196              26.100            0.016016   
21             3447920  3447920              20.600            0.201630   
22             3005973  3005973              21.700            0.121494   
23             3660308  3660308              23.900            0.044112   
24             3348144  3348144              23.900            0.044112   
25             3646046  3646046              21.300            0.146068   
26             3780693  3780693              26.989            0.010635   
27             2162173  2162173              19.300            0.366906   
28             3092312  3092312              22.600            0.080270   
29             3273782  3273782              23.800            0.046191   
...                ...      ...                 ...                 ...   
4657           3772757  3772757              26.312            0.014526   
4658           3766966  3766966              24.100            0.040230   
4659           3781002  3781002              22.477            0.084948   
4660           3678632  3678632              22.500            0.084053   
4661           3743745  3743745              26.500            0.013322   
4662           3744785  3744785              19.300            0.366906   
4663           3755345  3755345              21.500            0.133216   
4664           3772844  3772844              26.930            0.010928   
4665           2333578  2333578              20.200            0.242412   
4666           3425295  3425295              20.800            0.183889   
4667           3608622  3608622              24.300            0.036691   
4668           3475236  3475236              21.600            0.127220   
4669           3753832  3753832              19.100            0.402305   
4670           3756789  3756789              25.100            0.025384   
4671           3759277  3759277              23.400            0.055533   
4672           3753873  3753873              20.000            0.265800   
4673           3648764  3648764              22.600            0.080270   
4674           2068346  2068346              16.900            1.108039   
4675           3759005  3759005              26.300            0.014607   
4676           3759643  3759643              24.700            0.030518   
4677           3759644  3759644              24.500            0.033462   
4678           3358223  3358223

In [11]:
labels
labels = np.asarray(labels)
print (labels)

[[ True]
 [False]
 [ True]
 ...
 [False]
 [False]
 [False]]


In [12]:
X_train, X_test, y_train, y_test = train_test_split (features_transform, labels)

In [13]:
data.isnull().values.any()

False

In [14]:
model = SVC()
model.fit(X_train, y_train)

C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [15]:
y_pred = model.predict (X_test)

In [16]:
accuracy = accuracy_score (y_pred, y_test)
print (accuracy)

0.841296928327645


In [17]:
LRModel = LogisticRegression().fit(X_train, y_train)
LRPredict = LRModel.predict(X_test)

C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
accuracy = LRModel.score (X_test, y_test)

accuracy = accuracy_score (LRPredict, y_test)
print (accuracy)

NameError: name 'accuarcy_score' is not defined

In [17]:
treeModel = tree.DecisionTreeClassifier().fit (X_train, y_train)

In [18]:
treePredict = treeModel.predict (X_test)

In [19]:
accuracy = accuracy_score (treePredict, y_test)
print (accuracy)

0.9940273037542662


In [21]:
RFModel = RandomForestClassifier(random_state = 12).fit (X_train, y_train)
RFPredict = RFModel.predict(X_test)

C:\Users\Meghna\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Meghna\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


In [23]:
accuracy = accuracy_score (RFPredict, y_test)
accuracy

0.9931740614334471